/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToastRouteImport } from './routes/toast'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewRouteImport } from './routes/new'
import { Route as LinkRouteImport } from './routes/link'
import { Route as NoteIdRouteImport } from './routes/$noteId'
import { Route as IndexRouteImport } from './routes/index'

const ToastRoute = ToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/link': typeof LinkRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/toast': typeof ToastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/link': typeof LinkRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/toast': typeof ToastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/link': typeof LinkRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/toast': typeof ToastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$noteId' | '/link' | '/new' | '/search' | '/toast'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$noteId' | '/link' | '/new' | '/search' | '/toast'
  id: '__root__' | '/' | '/$noteId' | '/link' | '/new' | '/search' | '/toast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteIdRoute: typeof NoteIdRoute
  LinkRoute: typeof LinkRoute
  NewRoute: typeof NewRoute
  SearchRoute: typeof SearchRoute
  ToastRoute: typeof ToastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toast': {
      id: '/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof ToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$noteId': {
      id: '/$noteId'
      path: '/$noteId'
      fullPath: '/$noteId'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteIdRoute: NoteIdRoute,
  LinkRoute: LinkRoute,
  NewRoute: NewRoute,
  SearchRoute: SearchRoute,
  ToastRoute: ToastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
