// This file was generated by sticky-models. Do not edit this file manually.

export const MIN_WINDOW_WIDTH = 400;
export const MIN_WINDOW_HEIGHT = 115;
export const SEARCH_WINDOW_HEIGHT = 430;
export const COMMAND_WINDOW_HEIGHT = 480;
