// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnyModel = Note;

export type Note = {
  model: 'note';
  id: string;
  createdAt: string;
  updatedAt: string;
  content: string;
};
