//! Constants shared with the frontend.
//!
//! Like the ts-rs models, the constants are exported to TypeScript by
//! the test suite: `cargo test` regenerates `bindings/gen_constants.ts`
//! from the values below, so the two sides cannot drift.

macro_rules! shared_constants {
    ($($(#[$attr:meta])* pub const $name:ident: f64 = $value:expr;)*) => {
        $($(#[$attr])* pub const $name: f64 = $value;)*

        /// Every shared constant, in declaration order.
        #[cfg(test)]
        const ALL: &[(&str, f64)] = &[$((stringify!($name), $value)),*];
    };
}

shared_constants! {
    /// Minimum width of a note window; new notes also open at it.
    pub const MIN_WINDOW_WIDTH: f64 = 400.0;
    /// Minimum height of a note window; new notes also open at it.
    pub const MIN_WINDOW_HEIGHT: f64 = 115.0;
    /// Maximum height of the floating search panel; the frontend
    /// shrinks the window to fit its content.
    pub const SEARCH_WINDOW_HEIGHT: f64 = 430.0;
    /// Maximum height of the floating command palette; the frontend
    /// shrinks the window to fit its content.
    pub const COMMAND_WINDOW_HEIGHT: f64 = 480.0;
    /// Longest note display title, in characters; both the search
    /// results and the header title clamp to it.
    pub const MAX_TITLE_LEN: f64 = 100.0;
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_constants() {
        let mut out = String::from(
            "// This file was generated by sticky-models. \
             Do not edit this file manually.\n\n",
        );
        for (name, value) in super::ALL {
            out.push_str(&format!("export const {name} = {value};\n"));
        }

        let path =
            concat!(env!("CARGO_MANIFEST_DIR"), "/bindings/gen_constants.ts");
        std::fs::write(path, out).expect("failed to write gen_constants.ts");
    }
}
